-- PL/SQL の移行プロジェクト用の Oracle DDL。src/00_setup.sql の 5 表と sequence に、
-- 05 の emp_audit（監査ログ）、06 の bulk_target、05 の INSTEAD OF trigger が乗る view を足したもの。
-- 決定（2026-09-24）: 型の無い NUMBER の id 列（orders.order_id、order_items.order_id）は NUMBER(12) にする。
--   変換ツールは型の無い NUMBER を DOUBLE に写すが、キーに DOUBLE は使えないので、BIGINT になる精度を書く。
CREATE TABLE jobs (
  job_id      VARCHAR2(10)  CONSTRAINT jobs_pk PRIMARY KEY,
  job_title   VARCHAR2(35)  NOT NULL,
  min_salary  NUMBER(8,2),
  max_salary  NUMBER(8,2)
);

CREATE TABLE departments (
  department_id    NUMBER(4)     CONSTRAINT dept_pk PRIMARY KEY,
  department_name  VARCHAR2(30)  NOT NULL,
  manager_id       NUMBER(6),
  location         VARCHAR2(30)
);

CREATE TABLE employees (
  employee_id    NUMBER(6)     CONSTRAINT emp_pk PRIMARY KEY,
  first_name     VARCHAR2(20),
  last_name      VARCHAR2(25)  NOT NULL,
  email          VARCHAR2(25)  NOT NULL CONSTRAINT emp_email_uk UNIQUE,
  hire_date      DATE          NOT NULL,
  job_id         VARCHAR2(10)  NOT NULL CONSTRAINT emp_job_fk REFERENCES jobs,
  salary         NUMBER(8,2)   CONSTRAINT emp_salary_ck CHECK (salary > 0),
  commission_pct NUMBER(2,2),
  manager_id     NUMBER(6)     CONSTRAINT emp_mgr_fk  REFERENCES employees,
  department_id  NUMBER(4)     CONSTRAINT emp_dept_fk REFERENCES departments
);

CREATE INDEX emp_dept_ix ON employees (department_id);
CREATE INDEX emp_mgr_ix  ON employees (manager_id);

CREATE SEQUENCE emp_seq   START WITH 300 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE order_seq START WITH 1   INCREMENT BY 1;

CREATE TABLE orders (
  order_id     NUMBER(12)    DEFAULT order_seq.NEXTVAL CONSTRAINT orders_pk PRIMARY KEY,
  order_date   DATE          DEFAULT SYSDATE NOT NULL,
  employee_id  NUMBER(6)     CONSTRAINT orders_emp_fk REFERENCES employees,
  customer     VARCHAR2(40)  NOT NULL,
  status       VARCHAR2(10)  DEFAULT 'NEW'
               CONSTRAINT orders_status_ck CHECK (status IN ('NEW','SHIPPED','CANCELLED')),
  total        NUMBER(10,2)
);

CREATE TABLE order_items (
  order_id    NUMBER(12)   CONSTRAINT oi_order_fk REFERENCES orders ON DELETE CASCADE,
  line_no     NUMBER(3),
  product     VARCHAR2(40) NOT NULL,
  qty         NUMBER(5)    NOT NULL,
  unit_price  NUMBER(8,2)  NOT NULL,
  CONSTRAINT order_items_pk PRIMARY KEY (order_id, line_no)
);

CREATE TABLE emp_audit (
  audit_id     NUMBER(12) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  employee_id  NUMBER(6),
  action       VARCHAR2(10),
  old_salary   NUMBER(8,2),
  new_salary   NUMBER(8,2),
  changed_by   VARCHAR2(128) DEFAULT USER,
  changed_at   TIMESTAMP     DEFAULT SYSTIMESTAMP,
  message      VARCHAR2(4000)
);

CREATE TABLE bulk_target (
  employee_id NUMBER(6) PRIMARY KEY,
  last_name   VARCHAR2(25),
  salary      NUMBER(8,2) CONSTRAINT bulk_target_sal_ck CHECK (salary < 15000)
);

CREATE OR REPLACE VIEW emp_dept_upd_v AS
  SELECT e.employee_id, e.last_name, d.department_name
  FROM   employees e JOIN departments d ON d.department_id = e.department_id;
CREATE OR REPLACE TYPE emp_grade_t FORCE AS OBJECT (   -- FORCE: emp_grade_tab が依存していても作り直せる（deploy は何度でも流す）
  employee_id NUMBER,
  last_name   VARCHAR2(25),
  grade       VARCHAR2(1)
);

CREATE OR REPLACE TYPE emp_grade_tab AS TABLE OF emp_grade_t;

