"""#49: calling a routine that runs in a transaction of its own (`transactions.separate`).

The callee (an autonomous transaction in Oracle) must not join the caller's transaction: the caller takes a
`SeparateTransactions` port, builds the callee on the connection the port opens, and the callee's writes
survive the caller's rollback. Found with samples/oracle-samples b05_4 (2026-09-25).
"""

from __future__ import annotations

import pytest

from plsql.analysis import analyse as analyse_program
from plsql.gen_java import split
from plsql.gen_java.service import generate_module
from plsql.limits import Boundaries
from plsql.report import analyse

DDL = "CREATE TABLE emp_audit (audit_id NUMBER(12) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, message VARCHAR2(200));\n"

LOG = """
CREATE OR REPLACE PROCEDURE log_msg(p_msg VARCHAR2) AS
  PRAGMA AUTONOMOUS_TRANSACTION;
BEGIN
  INSERT INTO emp_audit (message) VALUES (p_msg);
  COMMIT;
END;
/
"""

CALLER = """
CREATE OR REPLACE PROCEDURE b05_4 AS
BEGIN
  log_msg('tried');
END;
/
"""


@pytest.fixture
def boundaries():
    previous = split._BOUNDARIES.get()
    split.set_boundaries(Boundaries(separate={"log_msg": "autonomous"}))
    yield
    split.set_boundaries(previous)


def test_the_caller_runs_the_callee_in_a_separate_transaction(tmp_path, boundaries):
    (tmp_path / "schema.sql").write_text(DDL, encoding="utf-8")
    (tmp_path / "log_msg.prc").write_text(LOG, encoding="utf-8")
    (tmp_path / "b05_4.prc").write_text(CALLER, encoding="utf-8")
    analysis = analyse(str(tmp_path), tmp_path / "schema.sql", boundaries=split._BOUNDARIES.get())
    analyse_program(analysis.program)   # resolves the calls, as the CLI does before generating
    caller = next(m for m in analysis.program.modules if m.name == "b05_4")
    java = generate_module(caller, "g.app", "g.infra", "g.domain", program=analysis.program).file.render()
    assert "private final SeparateTransactions separate;" in java, java
    assert "public B054Service(B054Repository repository, SeparateTransactions separate)" in java
    # without a ScalarDB schema no bind is lifted, so the callee's repository takes no Sequences here; with one
    # (samples/oracle-samples log_msg, whose emp_audit has an IDENTITY column) the caller takes and passes them
    assert 'separate.run(connection -> { new LogMsgService(new LogMsgRepository(connection)).logMsg("tried"); return null; });' in java, java
    assert "import g.infra.LogMsgRepository;" in java
    assert "UnsupportedOperationException" not in java
