"""DDL `DEFAULT` clauses: Oracle fills an omitted column, ScalarDB stores NULL, so the writer has to fill it.

Found with samples/oracle-samples (2026-09-25): `emp_audit.changed_by DEFAULT USER` / `changed_at DEFAULT
SYSTIMESTAMP` came back NULL from every generated INSERT that left them out, which the real-DB comparison
reported as a value difference on three scenarios. The fill lives next to the IDENTITY fill (`plsql.identity`)
because it is the same shape: a column the table used to provide, written by the application instead.
"""

from __future__ import annotations

import pathlib
import textwrap

import pytest

from plsql import identity
from plsql.ir import model as M
from plsql.symbols import OracleSchema

DDL = textwrap.dedent("""
    CREATE TABLE emp_audit (
      audit_id     NUMBER(12) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      employee_id  NUMBER(6),
      action       VARCHAR2(10),
      message      VARCHAR2(200),
      status       VARCHAR2(10)  DEFAULT 'NEW',
      note         VARCHAR2(10)  DEFAULT NULL,
      changed_by   VARCHAR2(128) DEFAULT USER,
      changed_at   TIMESTAMP     DEFAULT SYSTIMESTAMP
    );
    CREATE TABLE orders (
      order_id   NUMBER(12) DEFAULT order_seq.NEXTVAL PRIMARY KEY,
      order_date DATE DEFAULT SYSDATE NOT NULL,
      customer   VARCHAR2(30)
    );
""")


@pytest.fixture
def schema(tmp_path: pathlib.Path) -> OracleSchema:
    (tmp_path / "schema.sql").write_text(DDL, encoding="utf-8")
    return OracleSchema.from_ddl(tmp_path / "schema.sql")


def insert(sql: str) -> M.SqlOperation:
    return M.SqlOperation(id="r#stmt-1", kind="SqlOperation", sql_kind="INSERT", original_sql=sql)


def test_the_schema_records_every_default_but_null(schema):
    assert schema.defaults["emp_audit"] == {"status": "'NEW'", "changed_by": "USER", "changed_at": "SYSTIMESTAMP"}
    assert schema.defaults["orders"] == {"order_id": "order_seq.NEXTVAL", "order_date": "SYSDATE"}
    assert "note" not in schema.defaults["emp_audit"], "DEFAULT NULL is what an omitted column gets anyway"


def test_omitted_default_columns_are_written_into_the_insert(schema):
    statement = insert("INSERT INTO emp_audit (action, message) VALUES ('LOG', :p_msg)")
    identity._fill(statement, schema)
    sql = statement.original_sql.upper()
    assert "AUDIT_ID" in sql and "EMP_AUDIT_AUDIT_ID_IDENTITY.NEXTVAL" in sql, "the IDENTITY fill still happens"
    assert "STATUS" in sql and "'NEW'" in sql
    assert "CHANGED_BY" in sql and "USER" in sql
    assert "CHANGED_AT" in sql and "SYSTIMESTAMP" in sql
    codes = {d.code for d in statement.diagnostics}
    assert {"IDENTITY_FILLED", "DEFAULT_FILLED"} <= codes


def test_a_column_the_insert_gives_keeps_the_given_value(schema):
    statement = insert("INSERT INTO emp_audit (action, changed_by) VALUES ('LOG', 'batch')")
    identity._fill(statement, schema)
    sql = statement.original_sql.upper()
    assert sql.count("CHANGED_BY") == 1 and "'BATCH'" in sql
    assert "USER" not in sql.replace("CHANGED_BY", "")


def test_a_sequence_default_becomes_the_sequence_read(schema):
    statement = insert("INSERT INTO orders (customer) VALUES (:p_customer)")
    identity._fill(statement, schema)
    sql = statement.original_sql.upper()
    assert "ORDER_SEQ.NEXTVAL" in sql and "SYSDATE" in sql


def test_an_insert_without_a_column_list_is_left_alone(schema):
    statement = insert("INSERT INTO orders VALUES (1, SYSDATE, 'x')")
    before = statement.original_sql
    identity._fill(statement, schema)
    assert statement.original_sql == before and not statement.diagnostics


def test_the_lifted_default_reaches_the_audit_context():
    """End to end: the DEFAULT USER column is bound from `audit.user()`, like a spelled-out USER (#1)."""
    from plsql.gen_java.expr import translate
    from plsql.sqlbridge import lift_expressions
    import sqlglot

    statement = insert("INSERT INTO emp_audit (action) VALUES ('LOG')")
    schema = OracleSchema()
    schema.defaults = {"emp_audit": {"changed_by": "USER", "changed_at": "SYSTIMESTAMP"}}
    identity._fill(statement, schema)
    tree = sqlglot.parse_one(statement.original_sql, read="oracle")
    binds: list[M.BindVariable] = []
    lift_expressions(tree, binds, "scope", None)
    expressions = [b.expression for b in binds if b.expression]
    assert expressions == ["USER", "SYSTIMESTAMP"]
    assert all(translate(e).audit for e in expressions)


# --- INSERT ... RETURNING INTO (samples/oracle-samples emp_api.hire, 2026-09-25) --------------------------------
def test_a_returned_values_expression_is_assigned_before_the_insert():
    statement = insert("INSERT INTO employees (employee_id, last_name, email) "
                       "VALUES (emp_seq.NEXTVAL, :p_last, UPPER(:p_email)) RETURNING employee_id INTO v_id")
    before = identity._returned(statement)
    assert [ (s.kind, s.target, s.expression) for s in before ] == [("Assignment", "v_id", "emp_seq.NEXTVAL")]
    sql = statement.original_sql.upper()
    assert "RETURNING" not in sql and "V_ID" in sql and "NEXTVAL" not in sql
    assert {d.code for d in statement.diagnostics} == {"RETURNING_HOISTED"}


def test_a_returned_column_the_values_do_not_spell_out_is_left_alone():
    statement = insert("INSERT INTO employees (last_name) VALUES (:p_last) RETURNING employee_id INTO v_id")
    before = statement.original_sql
    assert identity._returned(statement) == [] and statement.original_sql == before


def test_the_rewrite_walks_nested_blocks(tmp_path):
    from plsql.ir import model as M
    inner = insert("INSERT INTO t (id) VALUES (s.NEXTVAL) RETURNING id INTO v")
    routine = M.Routine(id="r", kind="Routine", name="r", routine_kind="procedure",
                        body=[M.If(id="r#if", kind="If", branches=[M.Branch(condition="TRUE", body=[inner])])])
    program = M.Program(id="p", kind="Program",
                        modules=[M.Module(id="m", kind="Module", name="m", module_kind="procedure", routines=[routine])])
    identity.rewrite(program, None)
    body = routine.body[0].branches[0].body
    assert [s.kind for s in body] == ["Assignment", "SqlOperation"]
