--------------------------------------------------------------------------------
-- 05_plsql_units.sql : ストアドプロシージャ / ファンクション / パッケージ / トリガー
--   参照: PL/SQL Language Reference
--     Ch.9 Subprograms / Ch.10 Triggers / Ch.11 Packages
--     CREATE PROCEDURE / CREATE FUNCTION / CREATE PACKAGE / CREATE TRIGGER
--   前提: 00_setup.sql 実行済み
--------------------------------------------------------------------------------
SET ECHO ON
SET SERVEROUTPUT ON SIZE UNLIMITED
WHENEVER SQLERROR CONTINUE

-- 監査ログ表
CREATE TABLE emp_audit (
  audit_id     NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  employee_id  NUMBER,
  action       VARCHAR2(10),
  old_salary   NUMBER,
  new_salary   NUMBER,
  changed_by   VARCHAR2(128) DEFAULT USER,
  changed_at   TIMESTAMP     DEFAULT SYSTIMESTAMP,
  message      VARCHAR2(4000)
);

--==============================================================================
-- 1. プロシージャ（IN / OUT / IN OUT、既定値）
--==============================================================================
CREATE OR REPLACE PROCEDURE raise_salary (
  p_emp_id   IN     employees.employee_id%TYPE,
  p_pct      IN     NUMBER DEFAULT 5,
  p_new_sal     OUT employees.salary%TYPE
) AS
BEGIN
  UPDATE employees
  SET    salary = ROUND(salary * (1 + p_pct / 100), 2)
  WHERE  employee_id = p_emp_id
  RETURNING salary INTO p_new_sal;          -- 更新後の値を受け取る

  IF SQL%ROWCOUNT = 0 THEN
    RAISE_APPLICATION_ERROR(-20010, '社員が存在しません: ' || p_emp_id);
  END IF;
END raise_salary;
/
SHOW ERRORS

-- 呼び出し（位置指定・名前指定）
DECLARE
  v_new employees.salary%TYPE;
BEGIN
  raise_salary(104, 10, v_new);
  DBMS_OUTPUT.PUT_LINE('位置指定: ' || v_new);
  raise_salary(p_emp_id => 107, p_new_sal => v_new);     -- p_pct は既定値 5
  DBMS_OUTPUT.PUT_LINE('名前指定: ' || v_new);
  ROLLBACK;
END;
/

-- IN OUT パラメータ（NOCOPY で参照渡しのヒント）
CREATE OR REPLACE PROCEDURE normalize_name (p_name IN OUT NOCOPY VARCHAR2) AS
BEGIN
  p_name := INITCAP(TRIM(p_name));
END;
/

--==============================================================================
-- 2. ファンクション（SQL から呼び出し可能）
--==============================================================================
CREATE OR REPLACE FUNCTION annual_comp (
  p_salary IN NUMBER,
  p_comm   IN NUMBER DEFAULT NULL
) RETURN NUMBER
  DETERMINISTIC               -- 同じ入力なら同じ結果（ファンクション索引に必要）
AS
BEGIN
  RETURN p_salary * 12 * (1 + NVL(p_comm, 0));
END annual_comp;
/

-- 結果キャッシュ付きファンクション（参照系マスタの繰り返し参照向け）
CREATE OR REPLACE FUNCTION dept_name_of (p_dept_id IN NUMBER)
  RETURN VARCHAR2
  RESULT_CACHE
AS
  v_name departments.department_name%TYPE;
BEGIN
  SELECT department_name INTO v_name FROM departments WHERE department_id = p_dept_id;
  RETURN v_name;
EXCEPTION
  WHEN NO_DATA_FOUND THEN RETURN NULL;
END;
/

SELECT last_name, dept_name_of(department_id) AS dept, annual_comp(salary, commission_pct) AS annual
FROM   employees
ORDER  BY annual DESC;

--==============================================================================
-- 3. パッケージ（仕様部 / 本体、オーバーロード、プライベート、パッケージ変数、初期化部）
--==============================================================================
CREATE OR REPLACE PACKAGE emp_api AS
  -- 公開定数・型・例外
  c_max_raise_pct CONSTANT NUMBER := 20;
  TYPE t_emp_tab IS TABLE OF employees%ROWTYPE;
  e_invalid_raise EXCEPTION;

  -- 公開サブプログラム
  FUNCTION  hire (p_first VARCHAR2, p_last VARCHAR2, p_email VARCHAR2,
                  p_job VARCHAR2, p_salary NUMBER, p_dept NUMBER) RETURN NUMBER;
  PROCEDURE give_raise (p_emp_id NUMBER, p_pct NUMBER);
  PROCEDURE give_raise (p_dept_id NUMBER, p_pct NUMBER, p_by_dept BOOLEAN); -- オーバーロード
  FUNCTION  get_by_dept (p_dept_id NUMBER) RETURN SYS_REFCURSOR;
  FUNCTION  call_count RETURN PLS_INTEGER;
END emp_api;
/
SHOW ERRORS

CREATE OR REPLACE PACKAGE BODY emp_api AS
  -- プライベート変数（セッション単位で状態を保持）
  g_calls PLS_INTEGER := 0;

  -- プライベートプロシージャ
  PROCEDURE validate_pct (p_pct NUMBER) IS
  BEGIN
    g_calls := g_calls + 1;
    IF p_pct NOT BETWEEN 0 AND c_max_raise_pct THEN
      RAISE e_invalid_raise;
    END IF;
  END validate_pct;

  FUNCTION hire (p_first VARCHAR2, p_last VARCHAR2, p_email VARCHAR2,
                 p_job VARCHAR2, p_salary NUMBER, p_dept NUMBER) RETURN NUMBER IS
    v_id employees.employee_id%TYPE;
  BEGIN
    INSERT INTO employees (employee_id, first_name, last_name, email, hire_date,
                           job_id, salary, department_id)
    VALUES (emp_seq.NEXTVAL, p_first, p_last, UPPER(p_email), SYSDATE,
            p_job, p_salary, p_dept)
    RETURNING employee_id INTO v_id;
    RETURN v_id;
  EXCEPTION
    WHEN DUP_VAL_ON_INDEX THEN
      RAISE_APPLICATION_ERROR(-20020, 'メールアドレス重複: ' || p_email);
  END hire;

  PROCEDURE give_raise (p_emp_id NUMBER, p_pct NUMBER) IS
  BEGIN
    validate_pct(p_pct);
    UPDATE employees SET salary = salary * (1 + p_pct / 100) WHERE employee_id = p_emp_id;
  END give_raise;

  PROCEDURE give_raise (p_dept_id NUMBER, p_pct NUMBER, p_by_dept BOOLEAN) IS
  BEGIN
    validate_pct(p_pct);
    IF p_by_dept THEN
      UPDATE employees SET salary = salary * (1 + p_pct / 100) WHERE department_id = p_dept_id;
    END IF;
  END give_raise;

  FUNCTION get_by_dept (p_dept_id NUMBER) RETURN SYS_REFCURSOR IS
    rc SYS_REFCURSOR;
  BEGIN
    OPEN rc FOR
      SELECT employee_id, last_name, salary FROM employees
      WHERE  department_id = p_dept_id ORDER BY employee_id;
    RETURN rc;                                   -- 呼び出し側（Java 等）で結果セットとして受け取る
  END get_by_dept;

  FUNCTION call_count RETURN PLS_INTEGER IS
  BEGIN
    RETURN g_calls;
  END call_count;

BEGIN
  -- 初期化部：セッションで最初にパッケージが参照されたとき 1 回だけ実行
  g_calls := 0;
END emp_api;
/
SHOW ERRORS

DECLARE
  v_id NUMBER;
BEGIN
  v_id := emp_api.hire('Hanako', 'Sato', 'hsato', 'SA_REP', 8000, 80);
  DBMS_OUTPUT.PUT_LINE('採用ID: ' || v_id);
  emp_api.give_raise(v_id, 10);
  emp_api.give_raise(p_dept_id => 60, p_pct => 3, p_by_dept => TRUE);
  BEGIN
    emp_api.give_raise(v_id, 50);
  EXCEPTION
    WHEN emp_api.e_invalid_raise THEN DBMS_OUTPUT.PUT_LINE('昇給率が不正');
  END;
  DBMS_OUTPUT.PUT_LINE('validate 呼び出し回数: ' || emp_api.call_count);
  ROLLBACK;
END;
/

-- SQL*Plus / SQLcl で REF CURSOR を表示
VARIABLE rc REFCURSOR
EXEC :rc := emp_api.get_by_dept(60)
PRINT rc

--==============================================================================
-- 4. 自律型トランザクション（呼び出し元のロールバックに影響されないログ出力）[ORA]
--==============================================================================
CREATE OR REPLACE PROCEDURE log_msg (p_msg VARCHAR2) AS
  PRAGMA AUTONOMOUS_TRANSACTION;
BEGIN
  INSERT INTO emp_audit (action, message) VALUES ('LOG', p_msg);
  COMMIT;                                       -- 自身のトランザクションのみ確定
END;
/

BEGIN
  UPDATE employees SET salary = salary + 1 WHERE employee_id = 100;
  log_msg('社長の給与を変更しようとした');
  ROLLBACK;                                     -- UPDATE は戻るがログは残る
END;
/
SELECT action, message FROM emp_audit;

--==============================================================================
-- 5. トリガー
--==============================================================================
-- 5-1. BEFORE 行トリガー：値の補正と検証（:NEW / :OLD）
CREATE OR REPLACE TRIGGER emp_biu_trg
  BEFORE INSERT OR UPDATE OF salary, email ON employees
  FOR EACH ROW
BEGIN
  :NEW.email := UPPER(:NEW.email);
  IF UPDATING('SALARY') AND :NEW.salary < :OLD.salary * 0.5 THEN
    RAISE_APPLICATION_ERROR(-20030, '給与を半分未満に下げることはできません');
  END IF;
END;
/

-- 5-2. AFTER 行トリガー：監査ログ（条件付き WHEN 句）
CREATE OR REPLACE TRIGGER emp_salary_audit_trg
  AFTER UPDATE OF salary OR DELETE ON employees
  FOR EACH ROW
  WHEN (NEW.salary IS NULL OR OLD.salary <> NEW.salary)   -- WHEN 句ではコロン不要
BEGIN
  INSERT INTO emp_audit (employee_id, action, old_salary, new_salary)
  VALUES (:OLD.employee_id,
          CASE WHEN DELETING THEN 'DELETE' ELSE 'UPDATE' END,
          :OLD.salary, :NEW.salary);
END;
/

-- 5-3. 複合トリガー（11g+）：行ごとに収集して文の最後にまとめて処理
--      行トリガー内で同じ表を参照すると ORA-04091（変更表エラー）になる問題の定番回避策
CREATE OR REPLACE TRIGGER emp_dept_cap_trg
  FOR UPDATE OF salary ON employees
  COMPOUND TRIGGER
    TYPE t_ids IS TABLE OF employees.department_id%TYPE INDEX BY PLS_INTEGER;
    g_depts t_ids;

  AFTER EACH ROW IS
  BEGIN
    IF :NEW.department_id IS NOT NULL THEN
      g_depts(:NEW.department_id) := :NEW.department_id;
    END IF;
  END AFTER EACH ROW;

  AFTER STATEMENT IS
    v_total NUMBER;
    d       PLS_INTEGER := g_depts.FIRST;
  BEGIN
    WHILE d IS NOT NULL LOOP
      SELECT SUM(salary) INTO v_total FROM employees WHERE department_id = d;
      IF v_total > 200000 THEN
        RAISE_APPLICATION_ERROR(-20040, '部門 ' || d || ' の人件費上限超過');
      END IF;
      d := g_depts.NEXT(d);
    END LOOP;
  END AFTER STATEMENT;
END emp_dept_cap_trg;
/

-- 5-4. INSTEAD OF トリガー：結合ビューを更新可能にする
CREATE OR REPLACE VIEW emp_dept_upd_v AS
  SELECT e.employee_id, e.last_name, d.department_name
  FROM   employees e JOIN departments d ON d.department_id = e.department_id;

CREATE OR REPLACE TRIGGER emp_dept_upd_v_trg
  INSTEAD OF UPDATE ON emp_dept_upd_v
  FOR EACH ROW
BEGIN
  UPDATE employees
  SET    last_name     = :NEW.last_name,
         department_id = (SELECT department_id FROM departments
                          WHERE  department_name = :NEW.department_name)
  WHERE  employee_id   = :OLD.employee_id;
END;
/

-- 動作確認
UPDATE employees SET salary = salary * 1.01 WHERE department_id = 60;
UPDATE emp_dept_upd_v SET department_name = 'Sales' WHERE employee_id = 107;
SELECT employee_id, action, old_salary, new_salary FROM emp_audit WHERE action <> 'LOG';
ROLLBACK;

-- エラー確認（コンパイルエラーのあるオブジェクト）
SELECT name, type, line, position, text FROM user_errors ORDER BY name, sequence;
