"""A small Java writer: indentation, imports and a file header nobody edits by hand.

Templates are kept to a minimum on purpose (the plan's §3 says so). What a template cannot do is track the
imports a type needs, and getting those wrong is the most common way generated code fails to compile.
"""

from __future__ import annotations

from dataclasses import dataclass, field

# While the migration is running, the generated tree is rewritten from the rules on every change, so editing it
# by hand loses the edit at the next regeneration.
HEADER = (
    "// Generated by the PL/SQL migration tool. Do not edit.\n"
    "// Source: {source}\n"
    "// Every change belongs in the conversion rules or the generator, so that a regeneration keeps it.\n")

# P4-9: after handover the regeneration model ends (plan §9), and "do not edit" becomes false -- the code is
# the customer's to maintain. Saying otherwise would leave a banner telling maintainers not to do the thing
# they now have to do. What stays true is where the code came from, which is what makes it reviewable against
# the PL/SQL it replaced.
HANDOVER_HEADER = (
    "// Migrated from PL/SQL by the ScalarDB migration tool, {date}.\n"
    "// Source: {source}\n"
    "// This file is now maintained by hand: the tool is not run again after handover.\n"
    "// The `file:line` comments below point at the PL/SQL this came from; traceability.csv has the full map.\n")


# P4-9: which banner every file of this run carries. Module-level rather than a field, because the banner is a
# property of the run: a tree with both would be telling two different stories about who maintains it.
_BANNER = [HEADER, ""]


def set_banner(header: str, date: str = "") -> None:
    _BANNER[0], _BANNER[1] = header, date


def _banner() -> str:
    return _BANNER[0]


def _banner_date() -> str:
    return _BANNER[1]


@dataclass
class JavaFile:
    package: str
    name: str                       # class or record name
    source: str = ""                # the PL/SQL this came from
    imports: set[str] = field(default_factory=set)
    lines: list[str] = field(default_factory=list)
    _indent: int = 0

    def add_import(self, *names: str) -> None:
        self.imports.update(n for n in names if n and "." in n)

    def line(self, text: str = "") -> "JavaFile":
        self.lines.append(("    " * self._indent + text).rstrip() if text else "")
        return self

    def block(self, opening: str) -> "_Block":
        return _Block(self, opening)

    def comment(self, text: str) -> "JavaFile":
        for part in text.splitlines():
            self.line(f"// {part}")
        return self

    def render(self) -> str:
        head = [_banner().format(source=self.source or "(unknown)", date=_banner_date()),
                f"package {self.package};", ""]
        if self.imports:
            head += [f"import {i};" for i in sorted(self.imports)] + [""]
        return "\n".join(head + self.lines).rstrip() + "\n"

    @property
    def path(self) -> str:
        return f"{self.package.replace('.', '/')}/{self.name}.java"


class _Block:
    def __init__(self, file: JavaFile, opening: str) -> None:
        self.file = file
        self.opening = opening

    def __enter__(self) -> JavaFile:
        self.file.line(self.opening + " {")
        self.file._indent += 1
        return self.file

    def __exit__(self, *exc) -> None:
        self.file._indent -= 1
        self.file.line("}")
