-- sql-transpile のテスト用 SQL: DML と実用的な SELECT のパターン（変換元: Oracle Database）
-- 前半は表とデータの準備（3 方言で同じデータ）。後半がテスト対象の文で、3 方言で同じ番号（@id）の文は同じ操作をする。
-- 注釈:
--   @id               3 方言で共通の番号（I = INSERT、U = UPDATE、D = DELETE、S = SELECT、T = トランザクション）
--   @note             何を確かめるか
--   @check            DML の後に実行して結果を比べる問合せ
--   @expect-scalardb  ScalarDB SQL への変換結果（OK / WARN / PLANNED / ERROR）。tests/test_dml_examples.py が確かめる
-- 実行検証: .venv/bin/python difftest/transpile_verify.py --source oracle --examples-dir skills/sql-transpile/examples/dml

CREATE TABLE customers (customer_id NUMBER(6) PRIMARY KEY, name VARCHAR2(40), email VARCHAR2(60), region VARCHAR2(10), vip NUMBER(1), created_at DATE);
CREATE TABLE products (product_id NUMBER(6) PRIMARY KEY, name VARCHAR2(40), category VARCHAR2(20), price NUMBER(9,2), active NUMBER(1));
CREATE TABLE orders (order_id NUMBER(8) PRIMARY KEY, customer_id NUMBER(6), order_date DATE, status VARCHAR2(10) DEFAULT 'NEW', total NUMBER(10,2), note VARCHAR2(100));
CREATE INDEX idx_orders_customer ON orders (customer_id);
CREATE TABLE order_items (order_id NUMBER(8), line_no NUMBER(3), product_id NUMBER(6), qty NUMBER(5), unit_price NUMBER(9,2), PRIMARY KEY (order_id, line_no));
CREATE TABLE stock (warehouse_id NUMBER(4), product_id NUMBER(6), qty NUMBER(7), updated_at TIMESTAMP, PRIMARY KEY (warehouse_id, product_id));
CREATE TABLE audit_log (log_id NUMBER(10) GENERATED BY DEFAULT AS IDENTITY (START WITH 100) PRIMARY KEY, table_name VARCHAR2(30), action VARCHAR2(10), logged_at TIMESTAMP);
CREATE TABLE seq_counter (name VARCHAR2(30) PRIMARY KEY, next_val NUMBER(10));
CREATE SEQUENCE order_seq START WITH 5000;
INSERT INTO customers VALUES (1, 'Alice Smith', 'alice@example.com', 'EAST', 1, DATE '2024-01-10');
INSERT INTO customers VALUES (2, 'Bob Jones', 'bob@example.com', 'WEST', 0, DATE '2024-02-15');
INSERT INTO customers VALUES (3, 'Carol White', NULL, 'EAST', 0, DATE '2024-03-01');
INSERT INTO customers VALUES (4, 'Dave Brown', 'dave_b@example.com', 'NORTH', 1, DATE '2024-03-20');
INSERT INTO customers VALUES (5, 'Eve Black', 'eve%promo@example.com', 'WEST', 0, DATE '2024-04-05');
INSERT INTO customers VALUES (6, 'frank green', 'frank@example.com', NULL, 0, DATE '2024-05-12');
INSERT INTO products VALUES (101, 'Keyboard', 'PERIPHERAL', 49.99, 1);
INSERT INTO products VALUES (102, 'Mouse', 'PERIPHERAL', 19.50, 1);
INSERT INTO products VALUES (103, 'Monitor', 'DISPLAY', 199.00, 1);
INSERT INTO products VALUES (104, 'Laptop', 'COMPUTER', 1200.00, 1);
INSERT INTO products VALUES (105, 'USB Cable', 'ACCESSORY', 5.25, 0);
INSERT INTO products VALUES (106, 'Webcam', 'PERIPHERAL', NULL, 1);
INSERT INTO orders VALUES (1001, 1, DATE '2024-06-01', 'SHIPPED', 69.49, NULL);
INSERT INTO orders VALUES (1002, 1, DATE '2024-06-15', 'NEW', 199.00, 'gift');
INSERT INTO orders VALUES (1003, 2, DATE '2024-06-20', 'CANCELLED', 19.50, NULL);
INSERT INTO orders VALUES (1004, 3, DATE '2024-07-02', 'SHIPPED', 1249.99, NULL);
INSERT INTO orders VALUES (1005, 4, DATE '2024-07-10', 'NEW', 10.50, 'rush');
INSERT INTO orders VALUES (1006, 4, DATE '2024-07-11', 'PAID', 398.00, NULL);
INSERT INTO orders VALUES (1007, 5, DATE '2024-08-01', 'PAID', 1200.00, NULL);
INSERT INTO orders VALUES (1008, 2, DATE '2024-08-15', 'NEW', 0, NULL);
INSERT INTO order_items VALUES (1001, 1, 101, 1, 49.99);
INSERT INTO order_items VALUES (1001, 2, 102, 1, 19.50);
INSERT INTO order_items VALUES (1002, 1, 103, 1, 199.00);
INSERT INTO order_items VALUES (1003, 1, 102, 1, 19.50);
INSERT INTO order_items VALUES (1004, 1, 104, 1, 1200.00);
INSERT INTO order_items VALUES (1004, 2, 101, 1, 49.99);
INSERT INTO order_items VALUES (1005, 1, 105, 2, 5.25);
INSERT INTO order_items VALUES (1006, 1, 103, 2, 199.00);
INSERT INTO order_items VALUES (1007, 1, 104, 1, 1200.00);
INSERT INTO stock VALUES (1, 101, 50, TIMESTAMP '2024-08-01 09:00:00');
INSERT INTO stock VALUES (1, 102, 120, TIMESTAMP '2024-08-01 09:00:00');
INSERT INTO stock VALUES (1, 103, 15, TIMESTAMP '2024-08-01 09:00:00');
INSERT INTO stock VALUES (1, 104, 5, TIMESTAMP '2024-08-01 09:00:00');
INSERT INTO stock VALUES (2, 101, 30, TIMESTAMP '2024-08-01 09:00:00');
INSERT INTO stock VALUES (2, 103, 0, TIMESTAMP '2024-08-01 09:00:00');
INSERT INTO stock VALUES (2, 104, 8, TIMESTAMP '2024-08-01 09:00:00');
INSERT INTO stock VALUES (2, 105, 200, TIMESTAMP '2024-08-01 09:00:00');
INSERT INTO audit_log (log_id, table_name, action, logged_at) VALUES (1, 'orders', 'INSERT', TIMESTAMP '2024-08-01 10:00:00');
INSERT INTO audit_log (log_id, table_name, action, logged_at) VALUES (2, 'stock', 'UPDATE', TIMESTAMP '2024-08-01 11:00:00');
INSERT INTO seq_counter VALUES ('order_seq', 5000);

-- @tests
-- @id: I01
-- @note: 列リスト付きの 1 行 INSERT（主キーを含む）
-- @check: SELECT customer_id, name, email, region FROM customers WHERE customer_id = 7
-- @expect-scalardb: OK
INSERT INTO customers (customer_id, name, email, region, vip, created_at) VALUES (7, 'Grace Lee', 'grace@example.com', 'SOUTH', 0, DATE '2024-09-01');
-- @id: I02
-- @note: 列リストなしの INSERT（表定義の列順に依存する）
-- @check: SELECT product_id, name, category, price FROM products WHERE product_id = 107
-- @expect-scalardb: WARN
INSERT INTO products VALUES (107, 'Headset', 'PERIPHERAL', 79.00, 1);
-- @id: I03
-- @note: 複数行の INSERT（Oracle は INSERT ALL、PostgreSQL・MySQL は VALUES を並べる）
-- @check: SELECT order_id, line_no, product_id, qty FROM order_items WHERE order_id = 1008 ORDER BY line_no
-- @expect-scalardb: ERROR
INSERT ALL
  INTO order_items (order_id, line_no, product_id, qty, unit_price) VALUES (1008, 1, 102, 2, 19.50)
  INTO order_items (order_id, line_no, product_id, qty, unit_price) VALUES (1008, 2, 105, 3, 5.25)
SELECT * FROM dual;
-- @id: I04
-- @note: INSERT ... SELECT（別の表から行を写す）
-- @check: SELECT log_id, table_name, action FROM audit_log WHERE action = 'ARCHIVE' ORDER BY log_id
-- @expect-scalardb: ERROR
INSERT INTO audit_log (log_id, table_name, action, logged_at) SELECT order_id, 'orders', 'ARCHIVE', order_date FROM orders WHERE status = 'CANCELLED';
-- @id: I05
-- @note: VALUES の中の DEFAULT（列の既定値を使う。ScalarDB には既定値が無い）
-- @check: SELECT order_id, status, note FROM orders WHERE order_id = 1009
-- @expect-scalardb: ERROR
INSERT INTO orders (order_id, customer_id, order_date, status, total, note) VALUES (1009, 6, DATE '2024-09-02', DEFAULT, 0, NULL);
-- @id: I06
-- @note: 現在時刻を入れる（SYSTIMESTAMP / CURRENT_TIMESTAMP / NOW()）
-- @check: SELECT COUNT(*) AS n FROM audit_log WHERE log_id = 3 AND logged_at IS NOT NULL
-- @expect-scalardb: ERROR
INSERT INTO audit_log (log_id, table_name, action, logged_at) VALUES (3, 'customers', 'LOGIN', SYSTIMESTAMP);
-- @id: I07
-- @note: 採番列（IDENTITY / AUTO_INCREMENT）に任せて主キーを省く。表定義の変換が AUTO_INC で失敗するため、変換ツールは主キーの欠落を検出できない
-- @check: SELECT COUNT(*) AS n FROM audit_log WHERE action = 'EXPORT'
-- @expect-scalardb: WARN
INSERT INTO audit_log (table_name, action, logged_at) VALUES ('orders', 'EXPORT', TIMESTAMP '2024-09-03 12:00:00');
-- @id: I08
-- @note: シーケンスで主キーを採番（MySQL はシーケンスが無いので採番表を更新する）
-- @check: SELECT COUNT(*) AS n FROM orders WHERE customer_id = 3
-- @expect-scalardb: ERROR
INSERT INTO orders (order_id, customer_id, order_date, status, total, note) VALUES (order_seq.NEXTVAL, 3, DATE '2024-09-03', 'NEW', 5.25, NULL);
-- @id: I09
-- @note: あれば加算、無ければ挿入する upsert（列を参照する更新）
-- @check: SELECT qty FROM stock WHERE warehouse_id = 1 AND product_id = 102
-- @expect-scalardb: ERROR
MERGE INTO stock s
USING (SELECT 1 AS warehouse_id, 102 AS product_id, 10 AS qty FROM dual) src
ON (s.warehouse_id = src.warehouse_id AND s.product_id = src.product_id)
WHEN MATCHED THEN UPDATE SET s.qty = s.qty + src.qty
WHEN NOT MATCHED THEN INSERT (warehouse_id, product_id, qty) VALUES (src.warehouse_id, src.product_id, src.qty);
-- @id: I10
-- @note: あれば一部の列を上書き、無ければ挿入する upsert（UPSERT は全列を上書きする）
-- @check: SELECT product_id, name, category, price FROM products WHERE product_id = 102
-- @expect-scalardb: WARN
MERGE INTO products p
USING (SELECT 102 AS product_id, 'Mouse Pro' AS name, 'PERIPHERAL' AS category, 24.00 AS price, 1 AS active FROM dual) src
ON (p.product_id = src.product_id)
WHEN MATCHED THEN UPDATE SET p.name = src.name, p.price = src.price
WHEN NOT MATCHED THEN INSERT (product_id, name, category, price, active) VALUES (src.product_id, src.name, src.category, src.price, src.active);
-- @id: I11
-- @note: 無いときだけ挿入する（Oracle は NOT EXISTS、PostgreSQL は ON CONFLICT DO NOTHING、MySQL は INSERT IGNORE）
-- @check: SELECT customer_id, name FROM customers WHERE customer_id = 1
-- @expect-scalardb: ERROR
INSERT INTO customers (customer_id, name, email, region, vip, created_at)
SELECT 1, 'Alice Duplicate', NULL, 'EAST', 0, DATE '2024-09-04' FROM dual
WHERE NOT EXISTS (SELECT 1 FROM customers WHERE customer_id = 1);
-- @id: I12
-- @note: VALUES の中のスカラー副問合せ（別の表から単価を引く）
-- @check: SELECT order_id, line_no, unit_price FROM order_items WHERE order_id = 1005 ORDER BY line_no
-- @expect-scalardb: ERROR
INSERT INTO order_items (order_id, line_no, product_id, qty, unit_price) VALUES (1005, 2, 103, 1, (SELECT price FROM products WHERE product_id = 103));
-- @id: U01
-- @note: 主キーを指定した 1 行の UPDATE
-- @check: SELECT order_id, status FROM orders WHERE order_id = 1002
-- @expect-scalardb: OK
UPDATE orders SET status = 'SHIPPED' WHERE order_id = 1002;
-- @id: U02
-- @note: 複合主キーを指定した UPDATE（タイムスタンプのリテラル）
-- @check: SELECT qty, updated_at FROM stock WHERE warehouse_id = 1 AND product_id = 101
-- @expect-scalardb: WARN
UPDATE stock SET qty = 45, updated_at = TIMESTAMP '2024-09-01 10:00:00' WHERE warehouse_id = 1 AND product_id = 101;
-- @id: U03
-- @note: キー以外の条件で複数行を UPDATE（クロスパーティション走査になる）
-- @check: SELECT order_id, note FROM orders WHERE status = 'NEW' ORDER BY order_id
-- @expect-scalardb: WARN
UPDATE orders SET note = 'check' WHERE status = 'NEW';
-- @id: U04
-- @note: 現在の値を使う UPDATE（在庫を減らす。読んで計算して書く必要がある）
-- @check: SELECT qty FROM stock WHERE warehouse_id = 1 AND product_id = 103
-- @expect-scalardb: ERROR
UPDATE stock SET qty = qty - 5 WHERE warehouse_id = 1 AND product_id = 103;
-- @id: U05
-- @note: CASE で複数の列を条件付きで更新
-- @check: SELECT product_id, price, active FROM products ORDER BY product_id
-- @expect-scalardb: ERROR
UPDATE products SET price = CASE WHEN category = 'PERIPHERAL' THEN price * 0.9 ELSE price END, active = CASE WHEN price IS NULL THEN 0 ELSE active END WHERE category IN ('PERIPHERAL', 'ACCESSORY');
-- @id: U06
-- @note: SET の中の相関副問合せ（明細の合計で注文の合計を直す）
-- @check: SELECT order_id, total FROM orders WHERE order_id IN (1001, 1004) ORDER BY order_id
-- @expect-scalardb: ERROR
UPDATE orders o SET total = (SELECT COALESCE(SUM(i.qty * i.unit_price), 0) FROM order_items i WHERE i.order_id = o.order_id) WHERE o.order_id IN (1001, 1004);
-- @id: U07
-- @note: 別の表を条件にした UPDATE（Oracle は EXISTS、PostgreSQL は UPDATE ... FROM、MySQL は UPDATE ... JOIN）
-- @check: SELECT order_id, note FROM orders ORDER BY order_id
-- @expect-scalardb: ERROR
UPDATE orders o SET note = 'vip' WHERE EXISTS (SELECT 1 FROM customers c WHERE c.customer_id = o.customer_id AND c.vip = 1);
-- @id: U08
-- @note: NULL を設定し、IS NULL で絞る
-- @check: SELECT customer_id, email, region FROM customers WHERE customer_id = 6
-- @expect-scalardb: WARN
UPDATE customers SET email = NULL, region = 'UNKNOWN' WHERE region IS NULL;
-- @id: U09
-- @note: 主キーの IN と BETWEEN を組み合わせた UPDATE
-- @check: SELECT order_id, status FROM orders WHERE order_id IN (1005, 1008) ORDER BY order_id
-- @expect-scalardb: WARN
UPDATE orders SET status = 'PAID' WHERE order_id IN (1005, 1008) AND total BETWEEN 0 AND 100;
-- @id: U10
-- @note: 日付の加算（Oracle は日数の足し算、PostgreSQL は INTERVAL、MySQL は DATE_ADD）
-- @check: SELECT order_id, order_date FROM orders WHERE order_id = 1005
-- @expect-scalardb: ERROR
UPDATE orders SET order_date = order_date + 7 WHERE order_id = 1005;
-- @id: U11
-- @note: 並べた先頭 1 行だけを UPDATE（Oracle は ROWNUM、PostgreSQL は副問合せの LIMIT、MySQL は ORDER BY ... LIMIT）
-- @check: SELECT order_id, status FROM orders WHERE status = 'HOLD'
-- @expect-scalardb: ERROR
UPDATE orders SET status = 'HOLD' WHERE order_id = (SELECT order_id FROM (SELECT order_id FROM orders WHERE status = 'NEW' ORDER BY order_date, order_id) WHERE ROWNUM = 1);
-- @id: U12
-- @note: セカンダリインデックスの列で絞る UPDATE
-- @check: SELECT order_id, status FROM orders WHERE customer_id = 5
-- @expect-scalardb: OK
UPDATE orders SET status = 'CANCELLED' WHERE customer_id = 5;
-- @id: D01
-- @note: 複合主キーを指定した 1 行の DELETE
-- @check: SELECT COUNT(*) AS n FROM order_items WHERE order_id = 1003
-- @expect-scalardb: OK
DELETE FROM order_items WHERE order_id = 1003 AND line_no = 1;
-- @id: D02
-- @note: パーティションキーとクラスタリングキーの範囲で DELETE
-- @check: SELECT line_no FROM order_items WHERE order_id = 1004 ORDER BY line_no
-- @expect-scalardb: OK
DELETE FROM order_items WHERE order_id = 1004 AND line_no >= 2;
-- @id: D03
-- @note: キー以外の列の IN で DELETE（クロスパーティション走査になる）
-- @check: SELECT warehouse_id, product_id, qty FROM stock ORDER BY warehouse_id, product_id
-- @expect-scalardb: WARN
DELETE FROM stock WHERE qty IN (0, 200);
-- @id: D04
-- @note: WHERE の無い DELETE（全行）
-- @check: SELECT COUNT(*) AS n FROM audit_log
-- @expect-scalardb: WARN
DELETE FROM audit_log;
-- @id: D05
-- @note: EXISTS 副問合せで絞る DELETE（取り消された注文の明細）
-- @check: SELECT order_id, line_no FROM order_items ORDER BY order_id, line_no
-- @expect-scalardb: ERROR
DELETE FROM order_items i WHERE EXISTS (SELECT 1 FROM orders o WHERE o.order_id = i.order_id AND o.status = 'CANCELLED');
-- @id: D06
-- @note: NOT EXISTS で明細の無い注文を消す
-- @check: SELECT order_id FROM orders ORDER BY order_id
-- @expect-scalardb: ERROR
DELETE FROM orders WHERE NOT EXISTS (SELECT 1 FROM order_items i WHERE i.order_id = orders.order_id);
-- @id: D07
-- @note: 別の表を条件にした DELETE（Oracle は IN 副問合せ、PostgreSQL は USING、MySQL は複数表の DELETE）
-- @check: SELECT COUNT(*) AS n FROM order_items
-- @expect-scalardb: ERROR
DELETE FROM order_items WHERE order_id IN (SELECT order_id FROM orders WHERE status = 'CANCELLED');
-- @id: D08
-- @note: 並べた先頭 1 行だけを DELETE（Oracle は ROWNUM、PostgreSQL は副問合せの LIMIT、MySQL は ORDER BY ... LIMIT）
-- @check: SELECT log_id FROM audit_log ORDER BY log_id
-- @expect-scalardb: ERROR
DELETE FROM audit_log WHERE log_id IN (SELECT log_id FROM (SELECT log_id FROM audit_log ORDER BY logged_at, log_id) WHERE ROWNUM <= 1);
-- @id: D09
-- @note: 消した行を返す DELETE（PostgreSQL は RETURNING。Oracle と MySQL の SQL には無いので主キーで消すだけ）
-- @check: SELECT COUNT(*) AS n FROM orders WHERE order_id = 1003
-- @expect-scalardb: OK
DELETE FROM orders WHERE order_id = 1003;
-- @id: S01
-- @note: パーティションキーの等値とクラスタリングキーの範囲
-- @expect-scalardb: OK
SELECT line_no, product_id, qty FROM order_items WHERE order_id = 1004 AND line_no BETWEEN 1 AND 2 ORDER BY line_no;
-- @id: S02
-- @note: キーセットページング（Oracle は行値の比較が無いので OR で書く）
-- @expect-scalardb: WARN
SELECT order_id, line_no, qty FROM order_items WHERE order_id > 1004 OR (order_id = 1004 AND line_no > 1) ORDER BY order_id, line_no FETCH FIRST 3 ROWS ONLY;
-- @id: S03
-- @note: OFFSET ページング
-- @expect-scalardb: PLANNED
SELECT order_id, order_date FROM orders ORDER BY order_date, order_id OFFSET 2 ROWS FETCH NEXT 3 ROWS ONLY;
-- @id: S04
-- @note: 3 表の結合と集約・HAVING
-- @expect-scalardb: PLANNED
SELECT c.region, COUNT(DISTINCT o.order_id) AS orders, SUM(i.qty * i.unit_price) AS amount FROM customers c JOIN orders o ON o.customer_id = c.customer_id JOIN order_items i ON i.order_id = o.order_id WHERE o.status <> 'CANCELLED' GROUP BY c.region HAVING SUM(i.qty * i.unit_price) > 100 ORDER BY c.region;
-- @id: S05
-- @note: LEFT JOIN と IS NULL による反結合（明細の無い注文）
-- @expect-scalardb: PLANNED
SELECT o.order_id FROM orders o LEFT JOIN order_items i ON i.order_id = o.order_id WHERE i.order_id IS NULL ORDER BY o.order_id;
-- @id: S06
-- @note: SELECT 句の相関スカラー副問合せ
-- @expect-scalardb: PLANNED
SELECT c.customer_id, c.name, (SELECT COUNT(*) FROM orders o WHERE o.customer_id = c.customer_id) AS order_count FROM customers c ORDER BY c.customer_id;
-- @id: S07
-- @note: グループごとの上位 1 件（ROW_NUMBER）
-- @expect-scalardb: PLANNED
SELECT customer_id, order_id, total FROM (SELECT customer_id, order_id, total, ROW_NUMBER() OVER (PARTITION BY customer_id ORDER BY total DESC, order_id) AS rn FROM orders) t WHERE rn = 1 ORDER BY customer_id;
-- @id: S08
-- @note: CASE を使った条件付き集約
-- @expect-scalardb: PLANNED
SELECT customer_id, SUM(CASE WHEN status = 'NEW' THEN 1 ELSE 0 END) AS new_orders, SUM(CASE WHEN status IN ('PAID', 'SHIPPED') THEN total ELSE 0 END) AS paid_amount FROM orders GROUP BY customer_id ORDER BY customer_id;
-- @id: S09
-- @note: LIKE の ESCAPE（% を含むメールアドレス）
-- @expect-scalardb: WARN
SELECT customer_id, email FROM customers WHERE email LIKE '%!%%' ESCAPE '!' ORDER BY customer_id;
-- @id: S10
-- @note: 大文字小文字を区別しない検索（Oracle は UPPER、PostgreSQL は ILIKE、MySQL は既定の照合順序）
-- @expect-scalardb: PLANNED
SELECT customer_id, name FROM customers WHERE UPPER(name) LIKE 'FRANK%' ORDER BY customer_id;
-- @id: S11
-- @note: 月ごとに丸めて集計（Oracle は TRUNC、PostgreSQL は DATE_TRUNC、MySQL は DATE_FORMAT）
-- @expect-scalardb: PLANNED
SELECT TRUNC(order_date, 'MM') AS month, COUNT(*) AS n, SUM(total) AS amount FROM orders GROUP BY TRUNC(order_date, 'MM') ORDER BY month;
-- @id: S12
-- @note: NULL の並び位置を指定（MySQL には NULLS LAST が無い）
-- @expect-scalardb: WARN
SELECT product_id, price FROM products ORDER BY price DESC NULLS LAST, product_id;
-- @id: S13
-- @note: UNION ALL で 2 つの表の行を並べる
-- @expect-scalardb: PLANNED
SELECT customer_id AS id, 'customer' AS kind FROM customers WHERE region = 'EAST' UNION ALL SELECT product_id, 'product' FROM products WHERE category = 'DISPLAY' ORDER BY id;
-- @id: S14
-- @note: EXISTS による半結合（支払い済みの注文がある顧客）
-- @expect-scalardb: PLANNED
SELECT c.customer_id, c.name FROM customers c WHERE EXISTS (SELECT 1 FROM orders o WHERE o.customer_id = c.customer_id AND o.status = 'PAID') ORDER BY c.customer_id;
-- @id: S15
-- @note: FOR UPDATE で行をロックして読む
-- @expect-scalardb: WARN
SELECT qty FROM stock WHERE warehouse_id = 2 AND product_id = 104 FOR UPDATE;
-- @id: S16
-- @note: 真偽値の列で絞る（Oracle は NUMBER(1)、PostgreSQL は BOOLEAN、MySQL は TINYINT(1)）
-- @expect-scalardb: WARN
SELECT customer_id, name FROM customers WHERE vip = 1 ORDER BY customer_id;
-- @id: S17
-- @note: セカンダリインデックスで絞った集約
-- @expect-scalardb: OK
SELECT COUNT(*) AS n, SUM(total) AS amount FROM orders WHERE customer_id = 4;
-- @id: T01
-- @note: SAVEPOINT（ScalarDB にはセーブポイントが無い）
-- @expect-scalardb: ERROR
SAVEPOINT before_update;
