"""IDENTITY columns: the table numbered them; the target has no IDENTITY, so the writer draws the number.

`audit_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY` lets `INSERT INTO emp_audit (action, message)
VALUES (...)` leave the key out. ScalarDB SQL refuses an INSERT without its full primary key, so the column is
added here with `<table>_<column>_identity.NEXTVAL` as its value -- a sequence the generated code takes from
the same `Sequences` port as any other (`sequences.next("emp_audit_audit_id_identity")`). The policy for that
sequence comes from the DDL too (`plsql.sequences.Policies.from_ddl`). Found with samples/oracle-samples log_msg
(2026-09-25).
"""
from __future__ import annotations

import sqlglot
from sqlglot import exp

from .ir import model as M
from .lower import _walk
from .symbols import OracleSchema


def sequence_name(table: str, column: str) -> str:
    return f"{table.lower()}_{column.lower()}_identity"


def rewrite(program: M.Program, schema: OracleSchema | None) -> None:
    if schema is None or not schema.identity:
        return
    for module in program.modules:
        for routine in module.routines:
            statements = _walk(routine.body) + [s for h in routine.exception_handlers for s in _walk(h.body)]
            for statement in statements:
                if statement.kind != "SqlOperation" or (statement.sql_kind or "").upper() != "INSERT":
                    continue
                _fill(statement, schema)


def _fill(statement: M.SqlOperation, schema: OracleSchema) -> None:
    try:
        tree = sqlglot.parse_one(statement.original_sql or "", dialect="oracle")
    except Exception:
        return
    if not isinstance(tree, exp.Insert) or not isinstance(tree.this, exp.Schema):
        return   # no column list: every column is given, the identity one included
    table = tree.this.this.name.lower() if isinstance(tree.this.this, exp.Table) else None
    identity = schema.identity.get(table or "")
    if not identity:
        return
    columns = [c.name.lower() for c in tree.this.expressions]
    values = tree.expression
    tuples = values.expressions if isinstance(values, exp.Values) else []
    if not tuples:
        return   # INSERT ... SELECT: not this shape
    added = []
    for column in identity:
        if column in columns:
            continue
        tree.this.append("expressions", exp.to_identifier(column))
        for row in tuples:
            row.append("expressions", exp.column("NEXTVAL", table=sequence_name(table, column)))
        added.append(column)
    if not added:
        return
    statement.original_sql = tree.sql(dialect="oracle")
    statement.add("INFO", "IDENTITY_FILLED",
                  f"{table} の IDENTITY 列 {', '.join(added)} を INSERT に足した。値は "
                  f"{', '.join(sequence_name(table, c) for c in added)} から取る（移行先に IDENTITY は無い）")
