"""IDENTITY and DEFAULT columns: the table filled them; the target has neither, so the writer fills them.

`audit_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY` lets `INSERT INTO emp_audit (action, message)
VALUES (...)` leave the key out. ScalarDB SQL refuses an INSERT without its full primary key, so the column is
added here with `<table>_<column>_identity.NEXTVAL` as its value -- a sequence the generated code takes from
the same `Sequences` port as any other (`sequences.next("emp_audit_audit_id_identity")`). The policy for that
sequence comes from the DDL too (`plsql.sequences.Policies.from_ddl`). Found with samples/oracle-samples log_msg
(2026-09-25).

A `DEFAULT` clause is the same shape. `changed_by VARCHAR2(128) DEFAULT USER` / `changed_at TIMESTAMP DEFAULT
SYSTIMESTAMP` gave every omitted column a value on Oracle; on ScalarDB the same INSERT stores NULL, which is a
value difference the real-DB comparison showed (samples/oracle-samples raise_salary_ok, 2026-09-25). So the
DEFAULT expression is written into the INSERT as if the routine had spelled it out, and the usual lifting takes
it from there: `USER` and `SYSTIMESTAMP` become the caller's `AuditContext` (#1, #8), `SYSDATE` the pinned
clock, `seq.NEXTVAL` the `Sequences` port, a literal a literal. Nothing here decides what `USER` should mean
after the migration -- that is #1, and it is the caller's value either way.
"""
from __future__ import annotations

import sqlglot
from sqlglot import exp

from .ir import model as M
from .lower import _walk
from .symbols import OracleSchema


def sequence_name(table: str, column: str) -> str:
    return f"{table.lower()}_{column.lower()}_identity"


def rewrite(program: M.Program, schema: OracleSchema | None) -> None:
    if schema is None or not (schema.identity or schema.defaults):
        return
    for module in program.modules:
        for routine in module.routines:
            statements = _walk(routine.body) + [s for h in routine.exception_handlers for s in _walk(h.body)]
            for statement in statements:
                if statement.kind != "SqlOperation" or (statement.sql_kind or "").upper() != "INSERT":
                    continue
                _fill(statement, schema)


def _fill(statement: M.SqlOperation, schema: OracleSchema) -> None:
    try:
        tree = sqlglot.parse_one(statement.original_sql or "", dialect="oracle")
    except Exception:
        return
    if not isinstance(tree, exp.Insert) or not isinstance(tree.this, exp.Schema):
        return   # no column list: every column is given, the identity one included
    table = tree.this.this.name.lower() if isinstance(tree.this.this, exp.Table) else None
    identity = schema.identity.get(table or "")
    defaults = schema.defaults.get(table or "")
    if not identity and not defaults:
        return
    columns = [c.name.lower() for c in tree.this.expressions]
    values = tree.expression
    tuples = values.expressions if isinstance(values, exp.Values) else []
    if not tuples:
        return   # INSERT ... SELECT: not this shape
    added, defaulted = [], []
    for column in identity or {}:
        if column in columns:
            continue
        tree.this.append("expressions", exp.to_identifier(column))
        for row in tuples:
            row.append("expressions", exp.column("NEXTVAL", table=sequence_name(table, column)))
        added.append(column)
    for column, expression in (defaults or {}).items():
        if column in columns or column in added:
            continue
        try:
            value = sqlglot.parse_one(expression, dialect="oracle")
        except Exception:
            continue   # a DEFAULT the parser does not read stays a diagnostic in the schema, not a guess here
        tree.this.append("expressions", exp.to_identifier(column))
        for row in tuples:
            row.append("expressions", value.copy())
        defaulted.append((column, expression))
    if not added and not defaulted:
        return
    statement.original_sql = tree.sql(dialect="oracle")
    if added:
        statement.add("INFO", "IDENTITY_FILLED",
                      f"{table} の IDENTITY 列 {', '.join(added)} を INSERT に足した。値は "
                      f"{', '.join(sequence_name(table, c) for c in added)} から取る（移行先に IDENTITY は無い）")
    if defaulted:
        statement.add("INFO", "DEFAULT_FILLED",
                      f"{table} の DEFAULT 句を持つ列 {', '.join(c for c, _ in defaulted)} を INSERT に足した"
                      f"（{', '.join(f'{c} = {e}' for c, e in defaulted)}。移行先に DEFAULT は無く、省くと NULL になる）")
