# ScalarDB Cluster (standalone mode) -- licensed path. License key / cert come from environment variables.
scalar.db.cluster.node.standalone_mode.enabled=true
scalar.db.storage=jdbc
scalar.db.contact_points=jdbc:postgresql://backend-postgres:5432/scalardb
scalar.db.username=postgres
scalar.db.password=postgres
scalar.db.transaction_manager=consensus-commit
scalar.db.consensus_commit.isolation_level=SERIALIZABLE
scalar.db.cross_partition_scan.enabled=true
scalar.db.cross_partition_scan.filtering.enabled=true
scalar.db.cross_partition_scan.ordering.enabled=true
scalar.db.sql.enabled=true
